# Generated by Django 3.1.3 on 2020-11-16 16:43

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default='', max_length=256, verbose_name='ID')),
                ('label', models.CharField(default='', max_length=256, verbose_name='Label')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('thumbnail_url', models.URLField(blank=True, default='', verbose_name='Thumbnail URL')),
                ('published_t', models.DateTimeField(auto_now=True, null=True, verbose_name='Published')),
                ('is_complete', models.BooleanField(blank=True, default=False, verbose_name='Complete')),
                ('url', models.URLField(blank=True, default='', verbose_name='URL')),
                ('n_view', models.IntegerField(default=0, verbose_name='Nombre de vues')),
            ],
        ),
        migrations.CreateModel(
            name='ZPathNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=256, verbose_name='Label')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Complete')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='path.zpathnode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default='', max_length=256, verbose_name='ID')),
                ('etag', models.CharField(default='', max_length=256, verbose_name='Etag')),
                ('label', models.CharField(default='', max_length=256, verbose_name='Label')),
                ('url', models.URLField(blank=True, default='', verbose_name='URL')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('published_t', models.DateTimeField(blank=True, null=True, verbose_name='Published')),
                ('thumbnail_url', models.URLField(blank=True, default='', verbose_name='Thumbnail URL')),
                ('country', models.CharField(default='', max_length=7, verbose_name='Country')),
                ('is_4_kid', models.BooleanField(default=False, verbose_name='Pour enfant')),
                ('n_view', models.IntegerField(default=0, verbose_name='Nombre de vues')),
                ('n_subscriber', models.IntegerField(default=0, verbose_name="Nombre d'abonnés")),
                ('n_content', models.IntegerField(default=0, verbose_name='Nombre de contenus')),
                ('n_content_public', models.IntegerField(default=0, verbose_name='Nombre de contenus détectés')),
                ('paths', models.ManyToManyField(blank=True, related_name='sources', to='path.ZPathNode')),
            ],
        ),
        migrations.CreateModel(
            name='ZContentFile',
            fields=[
                ('zcontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='path.zcontent')),
            ],
            bases=('path.zcontent',),
        ),
        migrations.CreateModel(
            name='ZContentLink',
            fields=[
                ('zcontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='path.zcontent')),
            ],
            bases=('path.zcontent',),
        ),
        migrations.CreateModel(
            name='ZContentNode',
            fields=[
                ('zpathnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='path.zpathnode')),
            ],
            options={
                'abstract': False,
            },
            bases=('path.zpathnode',),
        ),
        migrations.CreateModel(
            name='ZContentQuiz',
            fields=[
                ('zcontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='path.zcontent')),
            ],
            bases=('path.zcontent',),
        ),
        migrations.CreateModel(
            name='ZContentText',
            fields=[
                ('zcontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='path.zcontent')),
            ],
            bases=('path.zcontent',),
        ),
        migrations.CreateModel(
            name='ZContentVideo',
            fields=[
                ('zcontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='path.zcontent')),
            ],
            bases=('path.zcontent',),
        ),
        migrations.CreateModel(
            name='ZPostNode',
            fields=[
                ('zpathnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='path.zpathnode')),
            ],
            options={
                'abstract': False,
            },
            bases=('path.zpathnode',),
        ),
        migrations.CreateModel(
            name='ZSourceBlog',
            fields=[
                ('zsource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='path.zsource')),
            ],
            bases=('path.zsource',),
        ),
        migrations.CreateModel(
            name='ZSourceYoutube',
            fields=[
                ('zsource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='path.zsource')),
            ],
            bases=('path.zsource',),
        ),
        migrations.AddField(
            model_name='zcontent',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='path.zsource'),
        ),
    ]
