# Generated by Django 3.1.3 on 2020-11-19 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ZSourceYoutube',
            new_name='ZYoutubeChannel',
        ),
        migrations.RenameModel(
            old_name='ZContentVideoYoutube',
            new_name='ZYoutubeVideo',
        ),
    ]
