# Generated by Django 3.1.2 on 2020-10-28 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZContentSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='', max_length=256, verbose_name='Label')),
                ('url', models.URLField(blank=True, default='', verbose_name='URL')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('n_content', models.IntegerField(blank=True, default=0, null=True, verbose_name='Nombre de contenus')),
            ],
        ),
        migrations.AddField(
            model_name='zpath',
            name='is_complete',
            field=models.TextField(blank=True, default='', verbose_name='Complete'),
        ),
        migrations.CreateModel(
            name='ZContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='', max_length=256, verbose_name='Label')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('is_complete', models.BooleanField(blank=True, default=False, verbose_name='Complete')),
                ('url', models.URLField(blank=True, default='', verbose_name='URL')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='path.zcontent')),
            ],
        ),
    ]
