# Generated by Django 3.1.3 on 2020-11-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zpath',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='Complete'),
        ),
    ]
