# Generated by Django 3.1.2 on 2020-11-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0002_auto_20201028_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='zcontentsource',
            name='identifier',
            field=models.CharField(default='', max_length=256, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='zcontentsource',
            name='paths',
            field=models.ManyToManyField(blank=True, null=True, related_name='sources', to='path.ZPath'),
        ),
    ]
