# Generated by Django 3.1.3 on 2020-11-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0002_auto_20201108_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zpath',
            name='label',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Label'),
        ),
    ]
