# Generated by Django 3.1.3 on 2020-11-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0003_tesypost'),
    ]

    operations = [
        migrations.AddField(
            model_name='zpathnode',
            name='model_type',
            field=models.CharField(choices=[('PATH', 'path'), ('POST', 'post'), ('CONTENT', (('VIDEO', 'video'), ('FILE', 'file')))], default='PATH', max_length=32, verbose_name='Type'),
        ),
    ]
