# Generated by Django 3.1.2 on 2020-11-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0003_auto_20201101_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='zcontentsource',
            name='etag',
            field=models.CharField(default='', max_length=256, verbose_name='Etag'),
        ),
        migrations.AlterField(
            model_name='zcontentsource',
            name='paths',
            field=models.ManyToManyField(blank=True, related_name='sources', to='path.ZPath'),
        ),
    ]
