# Generated by Django 3.1.2 on 2020-11-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0004_auto_20201101_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='zcontentsource',
            name='country',
            field=models.CharField(default='', max_length=7, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='zcontentsource',
            name='is_4_kid',
            field=models.BooleanField(default=False, verbose_name='Pour enfant'),
        ),
        migrations.AddField(
            model_name='zcontentsource',
            name='n_subscriber',
            field=models.IntegerField(default=0, verbose_name="Nombre d'abonnés"),
        ),
        migrations.AddField(
            model_name='zcontentsource',
            name='n_view',
            field=models.IntegerField(default=0, verbose_name='Nombre de vues'),
        ),
        migrations.AddField(
            model_name='zcontentsource',
            name='published_t',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Published'),
        ),
        migrations.AddField(
            model_name='zcontentsource',
            name='thumbnail',
            field=models.URLField(blank=True, default='', verbose_name='Thumbnail URL'),
        ),
        migrations.AlterField(
            model_name='zcontentsource',
            name='n_content',
            field=models.IntegerField(default=0, verbose_name='Nombre de contenus'),
        ),
    ]
