# Generated by Django 3.1.3 on 2020-11-19 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0004_zpathnode_model_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZPostNode',
        ),
        migrations.CreateModel(
            name='ZPostNode',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('path.zpathnode',),
        ),
    ]
