# Generated by Django 3.1.2 on 2020-11-01 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0005_auto_20201101_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zcontentsource',
            old_name='thumbnail',
            new_name='thumbnail_url',
        ),
    ]
