# Generated by Django 3.1.2 on 2020-11-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0007_auto_20201106_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='zcontent',
            name='published_t',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Published'),
        ),
        migrations.AddField(
            model_name='zcontent',
            name='thumbnail_url',
            field=models.URLField(blank=True, default='', verbose_name='Thumbnail URL'),
        ),
    ]
